name: skinbyfizza
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.11
  provider: ^6.1.2

  # Firebase Packages
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  
  # Google Sign In
  google_sign_in: ^6.2.1
  
  # Notifications
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.0
  flutter_timezone: ^3.0.1
  image_picker: ^1.2.1
  file_picker: ^8.0.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.PNG"

flutter:
  uses-material-design: true
